"""initial

Revision ID: cbb5704bc052
Revises: 
Create Date: 2023-01-16 14:20:48.861162

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cbb5704bc052"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
